language: go
sudo: false
go:
  - 1.9
before_install:
  - go get -t ./...
script:
  - make tag
before_deploy:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
deploy:
  provider: script
  script: make publish
  on:
    branch: master