namespace: your.namespace.to.register
name: yourappname
bot:
  botToken: You bot token here, do not prepend Bot... we'll do that for you
  authSrvNamespace: namespace that the auth-srv instance lives in
  discordServerId: https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-server-ID-
oauth:
  clientId: client_id
  clientSecret: client_secret
  callBackUrl: callback_url
net:
  listenHost: localhost
  listenPort: 80
serviceNames:
  authSrv: auth-srv
registry:
  hostname: localhost
  port: 8500