namespace: test.test.test
name: app
inputs:
  - slack
  - discord
registry:
  registerTtl: 20
  registerInterval: 20
chat:
  slack:
    debug: true
    token: 123456
  discord:
    token: Bot 123456
    whiteList:
    - "1234567890"
    - "2234567890"
    - "3234567890"
    prefix: "!"
