version: '3'
services:
  redis:
    image: "redis"

  consul:
    image: "consul"

  sig-cmd:
    image: "chremoas/sig-cmd:1.0.0"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul

  role-cmd:
    image: "chremoas/role-cmd:1.0.0"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - redis
      - consul

  role-srv:
    image: "chremoas/role-srv:1.0.0"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
