version: '3'
services:
 # services
  auth-srv:
    image: "chremoas/auth-srv:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  esi-srv:
    image: "chremoas/esi-srv:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  perms-srv:
    image: "chremoas/perms-srv:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  role-srv:
    image: "chremoas/role-srv:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

# commands
  auth-cmd:
    image: "chremoas/auth-cmd:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  filter-cmd:
    image: "chremoas/filter-cmd:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  lookup-cmd:
    image: "chremoas/lookup-cmd:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  perms-cmd:
    image: "chremoas/perms-cmd:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  role-cmd:
    image: "chremoas/role-cmd:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  sig-cmd:
    image: "chremoas/sig-cmd:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

# gateways
  discord-gateway:
    image: "chremoas/discord-gateway:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

# misc
  auth-web:
    image: "chremoas/auth-web:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    ports:
      - 3000:3000
    networks:
      - chremoas

  chremoas:
    image: "chremoas/chremoas:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

  auth-esi-poller:
    image: "chremoas/auth-esi-poller:latest"
    volumes:
      - /etc/chremoas:/etc/chremoas
    networks:
      - chremoas

networks:
  chremoas:
