version: '3'
services:
 # services
  auth-srv:
    image: "chremoas/auth-srv"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
      - mariadb
    networks:
      - chremoas

  esi-srv:
    image: "chremoas/esi-srv"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  perms-srv:
    image: "chremoas/perms-srv"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
      - redis
    networks:
      - chremoas

  role-srv:
    image: "chremoas/role-srv"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
      - redis
    networks:
      - chremoas

# commands
  auth-cmd:
    image: "chremoas/auth-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  filter-cmd:
    image: "chremoas/filter-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  lookup-cmd:
    image: "chremoas/lookup-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  perms-cmd:
    image: "chremoas/perms-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  role-cmd:
    image: "chremoas/role-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  sig-cmd:
    image: "chremoas/sig-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

# gateways
  discord-gateway:
    image: "chremoas/discord-gateway"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

# misc
  auth-web:
    image: "chremoas/auth-web"
    volumes:
      - /etc/chremoas:/etc/chremoas
    ports:
      - 3000:3000
    depends_on:
      - consul
    networks:
      - chremoas

  chremoas:
    image: "chremoas/chremoas"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  auth-esi-poller:
    image: "chremoas/auth-esi-poller"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

networks:
  chremoas: