version: '3'
services:
  redis:
    image: "redis"
    container_name: "chremoas-redis"
    volumes:
      - /etc/chremoas/redis:/data
    command: /data/redis.conf
    ports:
      - "6380:6379"
    networks:
      - chremoas

  consul:
    image: "consul"
    container_name: "chremoas-consul"
    ports:
      - "8501:8500"
    networks:
      - chremoas

  mariadb:
    image: "mariadb"
    container_name: "chremoas-mariadb"
    volumes:
      - /etc/chremoas/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /etc/chremoas/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - chremoas
    environment:
      MYSQL_ROOT_PASSWORD: chremoas
      MYSQL_DATABASE: chremoas
      MYSQL_USER: chremoas
      MYSQL_PASSWORD: chremoas

 # services
  auth-srv:
    image: "chremoas/auth-srv"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
      - mariadb
    networks:
      - chremoas

  esi-srv:
    image: "chremoas/esi-srv"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  perms-srv:
    image: "chremoas/perms-srv"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
      - redis
    networks:
      - chremoas

  role-srv:
    image: "chremoas/role-srv"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
      - redis
    networks:
      - chremoas

# commands
  auth-cmd:
    image: "chremoas/auth-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  filter-cmd:
    image: "chremoas/filter-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  lookup-cmd:
    image: "chremoas/lookup-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  perms-cmd:
    image: "chremoas/perms-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  role-cmd:
    image: "chremoas/role-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  sig-cmd:
    image: "chremoas/sig-cmd"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

# gateways
  discord-gateway:
    image: "chremoas/discord-gateway"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

# misc
  auth-web:
    image: "chremoas/auth-web"
    volumes:
      - /etc/chremoas:/etc/chremoas
    ports:
      - 3000:3000
    depends_on:
      - consul
    networks:
      - chremoas

  chremoas:
    image: "chremoas/chremoas"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

  auth-esi-poller:
    image: "chremoas/auth-esi-poller"
    volumes:
      - /etc/chremoas:/etc/chremoas
    depends_on:
      - consul
    networks:
      - chremoas

networks:
  chremoas: