// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bot.proto

/*
Package go_micro_bot is a generated protocol buffer package.

It is generated from these files:
	bot.proto

It has these top-level messages:
	HelpRequest
	HelpResponse
	ExecRequest
	ExecResponse
*/
package go_micro_bot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelpRequest struct {
}

func (m *HelpRequest) Reset()                    { *m = HelpRequest{} }
func (m *HelpRequest) String() string            { return proto.CompactTextString(m) }
func (*HelpRequest) ProtoMessage()               {}
func (*HelpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelpResponse struct {
	Usage       string `protobuf:"bytes,1,opt,name=usage" json:"usage,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *HelpResponse) Reset()                    { *m = HelpResponse{} }
func (m *HelpResponse) String() string            { return proto.CompactTextString(m) }
func (*HelpResponse) ProtoMessage()               {}
func (*HelpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelpResponse) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

func (m *HelpResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ExecRequest struct {
	Sender string   `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Args   []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (m *ExecRequest) Reset()                    { *m = ExecRequest{} }
func (m *ExecRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()               {}
func (*ExecRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExecRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ExecRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type ExecResponse struct {
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ExecResponse) Reset()                    { *m = ExecResponse{} }
func (m *ExecResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()               {}
func (*ExecResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ExecResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ExecResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*HelpRequest)(nil), "go.micro.bot.HelpRequest")
	proto.RegisterType((*HelpResponse)(nil), "go.micro.bot.HelpResponse")
	proto.RegisterType((*ExecRequest)(nil), "go.micro.bot.ExecRequest")
	proto.RegisterType((*ExecResponse)(nil), "go.micro.bot.ExecResponse")
}

func init() { proto.RegisterFile("bot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4a, 0xc4, 0x40,
	0x10, 0xc6, 0x2f, 0xe7, 0x19, 0xc9, 0x24, 0x36, 0x8b, 0x1c, 0xf1, 0xaa, 0xb0, 0xd5, 0x55, 0x5b,
	0x68, 0x25, 0x08, 0x16, 0xa2, 0x58, 0xe7, 0x0d, 0xf2, 0x67, 0x08, 0x81, 0x4b, 0x26, 0xce, 0x6c,
	0xc0, 0x77, 0xf0, 0xa5, 0x25, 0xbb, 0x5b, 0x2c, 0x87, 0x5d, 0x7e, 0x19, 0xe6, 0x37, 0xdf, 0xb7,
	0x90, 0xb5, 0x64, 0xcd, 0xc2, 0x64, 0x49, 0x15, 0x03, 0x99, 0x69, 0xec, 0x98, 0x4c, 0x4b, 0x56,
	0xdf, 0x43, 0xfe, 0x85, 0x97, 0xa5, 0xc6, 0xef, 0x15, 0xc5, 0xea, 0x4f, 0x28, 0x3c, 0xca, 0x42,
	0xb3, 0xa0, 0x7a, 0x80, 0xdb, 0x55, 0x9a, 0x01, 0xcb, 0xa4, 0x4a, 0xce, 0x59, 0xed, 0x41, 0x55,
	0x90, 0xf7, 0x28, 0x1d, 0x8f, 0x8b, 0x1d, 0x69, 0x2e, 0xf7, 0x6e, 0x16, 0xff, 0xd2, 0x2f, 0x90,
	0x7f, 0xfc, 0x60, 0x17, 0xb4, 0xea, 0x08, 0xa9, 0xe0, 0xdc, 0x23, 0x07, 0x4f, 0x20, 0xa5, 0xe0,
	0xd0, 0xf0, 0x20, 0xe5, 0xbe, 0xba, 0x39, 0x67, 0xb5, 0xfb, 0xd6, 0xaf, 0x50, 0xf8, 0xd5, 0x10,
	0xe1, 0x08, 0x29, 0xa3, 0xac, 0x17, 0xeb, 0x76, 0x8b, 0x3a, 0xd0, 0x16, 0x0d, 0x99, 0x89, 0xc3,
	0x79, 0x0f, 0x4f, 0xbf, 0x09, 0xdc, 0xbd, 0xd3, 0x34, 0x35, 0x73, 0xaf, 0xde, 0xe0, 0xb0, 0x95,
	0x51, 0x8f, 0x26, 0xae, 0x6c, 0xa2, 0xbe, 0xa7, 0xd3, 0x7f, 0x23, 0x7f, 0x58, 0xef, 0x36, 0xc1,
	0x16, 0xe5, 0x5a, 0x10, 0x35, 0xbb, 0x16, 0xc4, 0xc9, 0xf5, 0xae, 0x4d, 0xdd, 0x93, 0x3f, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x78, 0x68, 0x67, 0x86, 0x7f, 0x01, 0x00, 0x00,
}
